### ISSUE TITLE
Flaky MessageSplitReaderTest

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite-flink#43]
This test is flaky:

```
[INFO] Running com.google.cloud.pubsublite.flink.reader.MessageSplitReaderTest
13:35:06.896 [main] ERROR com.google.cloud.pubsublite.flink.reader.MessageSplitReader - Exception while trying to close subscribers
java.lang.RuntimeException: error
	at com.google.cloud.pubsublite.flink.reader.MessageSplitReader.closeAll(MessageSplitReader.java:141) ~[classes/:?]
	at com.google.cloud.pubsublite.flink.reader.MessageSplitReader.removeFinishedSubscribers(MessageSplitReader.java:87) [classes/:?]
	at com.google.cloud.pubsublite.flink.reader.MessageSplitReader.fetch(MessageSplitReader.java:108) [classes/:?]
	at com.google.cloud.pubsublite.flink.reader.MessageSplitReaderTest.testSplitFinishIgnoresCloseError(MessageSplitReaderTest.java:158) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55) [mockito-core-3.11.1.jar:?]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100) [mockito-core-3.11.1.jar:?]
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107) [mockito-core-3.11.1.jar:?]
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41) [mockito-core-3.11.1.jar:?]
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163) [mockito-core-3.11.1.jar:?]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
13:35:07.929 [main] ERROR com.google.cloud.pubsublite.flink.reader.MessageSplitReader - Adding split SubscriptionPartitionSplit{subscriptionPath=projects/3298749273/locations/europe-fake2-z/subscriptions/example-subscription, partition=Partition{value=33}, start=Offset{value=0}} which was already added to the fetcher
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.275 s - in com.google.cloud.pubsublite.flink.reader.MessageSplitReaderTest
[INFO] Running com.google.cloud.pubsublite.flink.reader.CompletablePullSubscriberImplTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in com.google.cloud.pubsublite.flink.reader.CompletablePullSubscriberImplTest
[INFO] Running com.google.cloud.pubsublite.flink.reader.PubsubLiteSourceReaderTest
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.35 s <<< FAILURE! - in com.google.cloud.pubsublite.flink.reader.PubsubLiteSourceReaderTest
Error:  com.google.cloud.pubsublite.flink.reader.PubsubLiteSourceReaderTest.testReader  Time elapsed: 0.346 s  <<< FAILURE!
com.google.common.truth.ComparisonFailureWithFacts: 
expected: END_OF_INPUT
but was : NOTHING_AVAILABLE
	at com.google.cloud.pubsublite.flink.reader.PubsubLiteSourceReaderTest.testReader(PubsubLiteSourceReaderTest.java:112)
```

**Comment by palmere-google** [comment]
fixed with https://github.com/googleapis/java-pubsublite-flink/pull/44
