### ISSUE TITLE
owl-bot postprocessor failed

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/java-pubsublite-flink#9]
The build log:
https://pantheon.corp.google.com/cloud-build/builds;region=global/133c996d-5017-499d-8e31-903afab4700e?project=repo-automation-bots

@SurferJeffAtGoogle FYI

**Comment by sofisl** [comment]
Another generation error occurred during the post-processor as well:

```
Generating missing pom.xml...
/owlbot
creating missing cloud pom.xml
creating missing bom pom.xml
updating modules in parent pom.xml
Traceback (most recent call last):
  File "/owlbot/src/fix-poms.py", line 402, in <module>
    main()
  File "/owlbot/src/fix-poms.py", line 380, in main
    update_parent_pom("pom.xml", modules)
  File "/owlbot/src/fix-poms.py", line 164, in update_parent_pom
    m.text for i, m in enumerate(existing) if m.text not in module_names
TypeError: 'NoneType' object is not iterable
```

https://pantheon.corp.google.com/cloud-build/builds;region=global/9c0a7705-794c-4a5b-92f3-19390ae4336b;step=9?project=repo-automation-bots

**Comment by sofisl** [comment]
post processor failed once more:

```
Traceback (most recent call last):
  File "/owlbot/src/fix-poms.py", line 402, in <module>
    main()
  File "/owlbot/src/fix-poms.py", line 380, in main
    update_parent_pom("pom.xml", modules)
  File "/owlbot/src/fix-poms.py", line 164, in update_parent_pom
    m.text for i, m in enumerate(existing) if m.text not in module_names
TypeError: 'NoneType' object is not iterable```

https://pantheon.corp.google.com/cloud-build/builds;region=global/65891e31-0de6-469f-9579-ff312a56d956;step=9?project=repo-automation-bots

**Comment by lesv** [comment]
It looks like there are no samples.
